=begin
#Treasury Prime API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'date'
require 'time'

module OpenapiClient
  class ApplyBusinessApplicationIdGetRequest
    attr_accessor :description

    attr_accessor :urls

    attr_accessor :bankdata

    attr_accessor :phone_number

    attr_accessor :tin

    attr_accessor :legal_structure

    attr_accessor :mailing_address

    attr_accessor :naics_description

    attr_accessor :name

    attr_accessor :physical_address

    attr_accessor :naics

    attr_accessor :incorporation_state

    attr_accessor :dba

    attr_accessor :document_ids

    attr_accessor :established_on

    attr_accessor :parent_businesses

    attr_accessor :person_applications

    attr_accessor :userdata

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'description' => :'description',
        :'urls' => :'urls',
        :'bankdata' => :'bankdata',
        :'phone_number' => :'phone_number',
        :'tin' => :'tin',
        :'legal_structure' => :'legal_structure',
        :'mailing_address' => :'mailing_address',
        :'naics_description' => :'naics_description',
        :'name' => :'name',
        :'physical_address' => :'physical_address',
        :'naics' => :'naics',
        :'incorporation_state' => :'incorporation_state',
        :'dba' => :'dba',
        :'document_ids' => :'document_ids',
        :'established_on' => :'established_on',
        :'parent_businesses' => :'parent_businesses',
        :'person_applications' => :'person_applications',
        :'userdata' => :'userdata'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'description' => :'String',
        :'urls' => :'Array',
        :'bankdata' => :'Object',
        :'phone_number' => :'UsPhone',
        :'tin' => :'TaxIdNumber',
        :'legal_structure' => :'Enum',
        :'mailing_address' => :'Struct',
        :'naics_description' => :'String',
        :'name' => :'String',
        :'physical_address' => :'Struct',
        :'naics' => :'String',
        :'incorporation_state' => :'String',
        :'dba' => :'String',
        :'document_ids' => :'Array',
        :'established_on' => :'Date',
        :'parent_businesses' => :'Array',
        :'person_applications' => :'Array',
        :'userdata' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::ApplyBusinessApplicationIdGetRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::ApplyBusinessApplicationIdGetRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'urls')
        self.urls = attributes[:'urls']
      end

      if attributes.key?(:'bankdata')
        self.bankdata = attributes[:'bankdata']
      end

      if attributes.key?(:'phone_number')
        self.phone_number = attributes[:'phone_number']
      end

      if attributes.key?(:'tin')
        self.tin = attributes[:'tin']
      end

      if attributes.key?(:'legal_structure')
        self.legal_structure = attributes[:'legal_structure']
      end

      if attributes.key?(:'mailing_address')
        self.mailing_address = attributes[:'mailing_address']
      end

      if attributes.key?(:'naics_description')
        self.naics_description = attributes[:'naics_description']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'physical_address')
        self.physical_address = attributes[:'physical_address']
      end

      if attributes.key?(:'naics')
        self.naics = attributes[:'naics']
      end

      if attributes.key?(:'incorporation_state')
        self.incorporation_state = attributes[:'incorporation_state']
      end

      if attributes.key?(:'dba')
        self.dba = attributes[:'dba']
      end

      if attributes.key?(:'document_ids')
        self.document_ids = attributes[:'document_ids']
      end

      if attributes.key?(:'established_on')
        self.established_on = attributes[:'established_on']
      end

      if attributes.key?(:'parent_businesses')
        self.parent_businesses = attributes[:'parent_businesses']
      end

      if attributes.key?(:'person_applications')
        self.person_applications = attributes[:'person_applications']
      end

      if attributes.key?(:'userdata')
        self.userdata = attributes[:'userdata']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          description == o.description &&
          urls == o.urls &&
          bankdata == o.bankdata &&
          phone_number == o.phone_number &&
          tin == o.tin &&
          legal_structure == o.legal_structure &&
          mailing_address == o.mailing_address &&
          naics_description == o.naics_description &&
          name == o.name &&
          physical_address == o.physical_address &&
          naics == o.naics &&
          incorporation_state == o.incorporation_state &&
          dba == o.dba &&
          document_ids == o.document_ids &&
          established_on == o.established_on &&
          parent_businesses == o.parent_businesses &&
          person_applications == o.person_applications &&
          userdata == o.userdata
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [description, urls, bankdata, phone_number, tin, legal_structure, mailing_address, naics_description, name, physical_address, naics, incorporation_state, dba, document_ids, established_on, parent_businesses, person_applications, userdata].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
