=begin
#Treasury Prime API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'date'
require 'time'

module OpenapiClient
  class SettingGet200ResponseInner
    attr_accessor :ach_limit_credit

    attr_accessor :id

    attr_accessor :wire_approvals

    attr_accessor :wire_daily_limit

    attr_accessor :ach_limit_debit

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'ach_limit_credit' => :'ach_limit_credit',
        :'id' => :'id',
        :'wire_approvals' => :'wire_approvals',
        :'wire_daily_limit' => :'wire_daily_limit',
        :'ach_limit_debit' => :'ach_limit_debit'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'ach_limit_credit' => :'String',
        :'id' => :'String',
        :'wire_approvals' => :'Integer',
        :'wire_daily_limit' => :'String',
        :'ach_limit_debit' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::SettingGet200ResponseInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::SettingGet200ResponseInner`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'ach_limit_credit')
        self.ach_limit_credit = attributes[:'ach_limit_credit']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'wire_approvals')
        self.wire_approvals = attributes[:'wire_approvals']
      end

      if attributes.key?(:'wire_daily_limit')
        self.wire_daily_limit = attributes[:'wire_daily_limit']
      end

      if attributes.key?(:'ach_limit_debit')
        self.ach_limit_debit = attributes[:'ach_limit_debit']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      pattern = Regexp.new(/^-?[0-9]+[.][0-9][0-9]$/)
      if !@ach_limit_credit.nil? && @ach_limit_credit !~ pattern
        invalid_properties.push("invalid value for \"ach_limit_credit\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^-?[0-9]+[.][0-9][0-9]$/)
      if !@wire_daily_limit.nil? && @wire_daily_limit !~ pattern
        invalid_properties.push("invalid value for \"wire_daily_limit\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^-?[0-9]+[.][0-9][0-9]$/)
      if !@ach_limit_debit.nil? && @ach_limit_debit !~ pattern
        invalid_properties.push("invalid value for \"ach_limit_debit\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@ach_limit_credit.nil? && @ach_limit_credit !~ Regexp.new(/^-?[0-9]+[.][0-9][0-9]$/)
      return false if !@wire_daily_limit.nil? && @wire_daily_limit !~ Regexp.new(/^-?[0-9]+[.][0-9][0-9]$/)
      return false if !@ach_limit_debit.nil? && @ach_limit_debit !~ Regexp.new(/^-?[0-9]+[.][0-9][0-9]$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] ach_limit_credit Value to be assigned
    def ach_limit_credit=(ach_limit_credit)
      pattern = Regexp.new(/^-?[0-9]+[.][0-9][0-9]$/)
      if !ach_limit_credit.nil? && ach_limit_credit !~ pattern
        fail ArgumentError, "invalid value for \"ach_limit_credit\", must conform to the pattern #{pattern}."
      end

      @ach_limit_credit = ach_limit_credit
    end

    # Custom attribute writer method with validation
    # @param [Object] wire_daily_limit Value to be assigned
    def wire_daily_limit=(wire_daily_limit)
      pattern = Regexp.new(/^-?[0-9]+[.][0-9][0-9]$/)
      if !wire_daily_limit.nil? && wire_daily_limit !~ pattern
        fail ArgumentError, "invalid value for \"wire_daily_limit\", must conform to the pattern #{pattern}."
      end

      @wire_daily_limit = wire_daily_limit
    end

    # Custom attribute writer method with validation
    # @param [Object] ach_limit_debit Value to be assigned
    def ach_limit_debit=(ach_limit_debit)
      pattern = Regexp.new(/^-?[0-9]+[.][0-9][0-9]$/)
      if !ach_limit_debit.nil? && ach_limit_debit !~ pattern
        fail ArgumentError, "invalid value for \"ach_limit_debit\", must conform to the pattern #{pattern}."
      end

      @ach_limit_debit = ach_limit_debit
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          ach_limit_credit == o.ach_limit_credit &&
          id == o.id &&
          wire_approvals == o.wire_approvals &&
          wire_daily_limit == o.wire_daily_limit &&
          ach_limit_debit == o.ach_limit_debit
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [ach_limit_credit, id, wire_approvals, wire_daily_limit, ach_limit_debit].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
