=begin
#Treasury Prime API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/account_get200_response'
require 'openapi_client/models/account_get200_response_inner'
require 'openapi_client/models/account_get_request'
require 'openapi_client/models/account_id_active_holds_get200_response'
require 'openapi_client/models/account_id_delete200_response'
require 'openapi_client/models/account_id_delete_request'
require 'openapi_client/models/account_id_statement_get200_response'
require 'openapi_client/models/account_id_tax_document_file_id_get200_response'
require 'openapi_client/models/account_id_tax_document_get200_response'
require 'openapi_client/models/account_number_post200_response'
require 'openapi_client/models/account_number_post_request'
require 'openapi_client/models/account_number_reservation_get200_response_inner'
require 'openapi_client/models/account_product_get200_response_inner'
require 'openapi_client/models/ach_get200_response_inner'
require 'openapi_client/models/ach_get_request'
require 'openapi_client/models/ach_id_get_request'
require 'openapi_client/models/apply_account_application_get_request'
require 'openapi_client/models/apply_account_application_id_get200_response'
require 'openapi_client/models/apply_account_application_id_get_request'
require 'openapi_client/models/apply_additional_person_application_get_request'
require 'openapi_client/models/apply_additional_person_application_id_get200_response'
require 'openapi_client/models/apply_additional_person_application_id_get_request'
require 'openapi_client/models/apply_authorized_user_application_get200_response_inner'
require 'openapi_client/models/apply_authorized_user_application_get_request'
require 'openapi_client/models/apply_authorized_user_application_id_get_request'
require 'openapi_client/models/apply_business_application_get_request'
require 'openapi_client/models/apply_business_application_id_get200_response'
require 'openapi_client/models/apply_business_application_id_get_request'
require 'openapi_client/models/apply_compliance_get200_response_inner'
require 'openapi_client/models/apply_compliance_get_request'
require 'openapi_client/models/apply_deposit_get_request'
require 'openapi_client/models/apply_deposit_id_get200_response'
require 'openapi_client/models/apply_kyc_get_request'
require 'openapi_client/models/apply_kyc_id_get200_response'
require 'openapi_client/models/apply_kyc_product_get200_response_inner'
require 'openapi_client/models/apply_kyc_product_get_request'
require 'openapi_client/models/apply_kyc_product_id_get_request'
require 'openapi_client/models/apply_parent_business_get_request'
require 'openapi_client/models/apply_parent_business_id_get200_response'
require 'openapi_client/models/apply_parent_business_id_get_request'
require 'openapi_client/models/apply_person_application_get200_response_inner'
require 'openapi_client/models/apply_person_application_get_request'
require 'openapi_client/models/apply_person_application_id_get_request'
require 'openapi_client/models/billpay_counterparty_get_request'
require 'openapi_client/models/billpay_counterparty_id_get200_response'
require 'openapi_client/models/billpay_counterparty_id_get_request'
require 'openapi_client/models/billpay_merchant_get200_response'
require 'openapi_client/models/billpay_payment_get_request'
require 'openapi_client/models/billpay_payment_id_get200_response'
require 'openapi_client/models/billpay_payment_id_get_request'
require 'openapi_client/models/billpay_rule_get_request'
require 'openapi_client/models/billpay_rule_id_get200_response'
require 'openapi_client/models/billpay_rule_id_get_request'
require 'openapi_client/models/book_get200_response_inner'
require 'openapi_client/models/book_get_request'
require 'openapi_client/models/book_id_get_request'
require 'openapi_client/models/business_id_get200_response'
require 'openapi_client/models/business_id_get_request'
require 'openapi_client/models/card_auth_loop_endpoint_get200_response_inner'
require 'openapi_client/models/card_auth_loop_endpoint_get_request'
require 'openapi_client/models/card_auth_loop_endpoint_id_delete_request'
require 'openapi_client/models/card_card_id_digital_wallet_token_google_pay_post200_response'
require 'openapi_client/models/card_card_id_digital_wallet_token_google_pay_post_request'
require 'openapi_client/models/card_charge_get_request'
require 'openapi_client/models/card_charge_id_get200_response'
require 'openapi_client/models/card_event_id_get200_response'
require 'openapi_client/models/card_get200_response_inner'
require 'openapi_client/models/card_get_request'
require 'openapi_client/models/card_id_get_request'
require 'openapi_client/models/card_id_token_get200_response'
require 'openapi_client/models/cardproduct_id_get200_response'
require 'openapi_client/models/cardproduct_id_get_request'
require 'openapi_client/models/check_deposit_get200_response_inner'
require 'openapi_client/models/check_deposit_get_request'
require 'openapi_client/models/check_deposit_person_get_request'
require 'openapi_client/models/check_deposit_person_id_get200_response'
require 'openapi_client/models/check_get200_response_inner'
require 'openapi_client/models/check_get_request'
require 'openapi_client/models/check_image_get200_response_inner'
require 'openapi_client/models/counterparty_get_request'
require 'openapi_client/models/counterparty_id_get200_response'
require 'openapi_client/models/counterparty_id_get_request'
require 'openapi_client/models/document_get200_response_inner'
require 'openapi_client/models/document_get_request'
require 'openapi_client/models/document_id_get_request'
require 'openapi_client/models/file_id_content_get200_response'
require 'openapi_client/models/person_id_card_get200_response'
require 'openapi_client/models/person_id_card_get200_response1'
require 'openapi_client/models/person_id_card_get_request'
require 'openapi_client/models/person_id_get200_response'
require 'openapi_client/models/person_id_get_request'
require 'openapi_client/models/plaid_exchange_users_auth_token_post200_response'
require 'openapi_client/models/plaid_exchange_users_user_id2fa_post200_response'
require 'openapi_client/models/plaid_exchange_users_user_id_get200_response'
require 'openapi_client/models/plaid_exchange_users_user_id_transactions_get200_response'
require 'openapi_client/models/reserve_get200_response_inner'
require 'openapi_client/models/reserve_get_request'
require 'openapi_client/models/reserve_id_delete_request'
require 'openapi_client/models/search_get200_response_inner'
require 'openapi_client/models/setting_get200_response_inner'
require 'openapi_client/models/setting_get_request'
require 'openapi_client/models/simulation_post200_response'
require 'openapi_client/models/simulation_post_request'
require 'openapi_client/models/survey_get200_response_inner'
require 'openapi_client/models/third_party_ach_get200_response_inner'
require 'openapi_client/models/third_party_ach_get_request'
require 'openapi_client/models/third_party_ach_id_get_request'
require 'openapi_client/models/transaction_id_get200_response'
require 'openapi_client/models/webhook_get200_response_inner'
require 'openapi_client/models/webhook_get_request'
require 'openapi_client/models/webhook_id_delete_request'
require 'openapi_client/models/wire_get200_response_inner'
require 'openapi_client/models/wire_get_request'
require 'openapi_client/models/wire_id_get_request'

# APIs
require 'openapi_client/api/default_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
